apiVersion: v2
name: bambu-stream
description: Helm chart for the Bambu P2S FastAPI stream service
type: application
version: 0.1.0
appVersion: "0.2.0"
dependencies:
  - name: nodejs
    alias: application
    version: v1.1.0
    repository: https://charts.silte.fi
